codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 90..100

  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch: no
    changes: no

comment: off
