# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py
  # Temporarily turning off to get docs build passing
  # fail_on_warning: true

python:
  install:
    - requirements: docs/requirements-docs.txt
    - method: pip
      path: .
