# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2023.3.2.dev4+g33c58694e.d20230313'
__version_tuple__ = version_tuple = (2023, 3, 2, 'dev4', 'g33c58694e.d20230313')
