package:
  name: msgpack-python
  version: "1.2.0rc1"

source:
  url: https://files.pythonhosted.org/packages/74/da/44cc218890c9ee7c82375051971b21d8099935d6b60b4aea2448f1dd21fd/msgpack-1.2.0rc1.tar.gz
  sha256: 849f89207974443eab7b9fb5504e0c2dfff1f0cbefd3d2cdeb05140f0d70b97e

build:
  script: python -m pip install . -vv --no-deps --no-build-isolation --prefix=$PREFIX
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - python
    - pip
    - setuptools >=69.5.1
    - cython >=3.0.11,<3.1.0
  # host:
  #   - python
  # run:
  #   - python

tests:
  - python:
      imports: [msgpack]
