package:
  name: jmespath
  version: "0.9.0"

source:
  fn: jmespath-0.9.0.tar.gz
  url: https://pypi.python.org/packages/source/j/jmespath/jmespath-0.9.0.tar.gz
  md5: 471b7d19bd153ac11a21d4fb7466800c

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - jmespath

about:
  home: https://github.com/jmespath/jmespath.py
  license: MIT License
  summary: 'JSON Matching Expressions'
