"""Slicing operations."""

from dask.array._array_expr._slicing import (
    BooleanIndexFlattened,
    SetItem,
    Slice,
    SliceSlicesIntegers,
    SlicesWrapNone,
    Squeeze,
    TakeUnknownOneChunk,
    VIndexArray,
    _numpy_vindex,
    _vindex,
    _vindex_array,
    normalize_index,
    slice_array,
    slice_slices_and_integers,
    slice_with_bool_dask_array,
    slice_with_int_dask_array,
    slice_with_int_dask_array_on_axis,
    slice_with_newaxes,
    slice_wrap_lists,
    squeeze,
    take,
)

__all__ = [
    "slice_array",
    "slice_with_newaxes",
    "slice_wrap_lists",
    "slice_slices_and_integers",
    "slice_with_int_dask_array",
    "slice_with_int_dask_array_on_axis",
    "slice_with_bool_dask_array",
    "take",
    "squeeze",
    "Slice",
    "SliceSlicesIntegers",
    "SlicesWrapNone",
    "TakeUnknownOneChunk",
    "Squeeze",
    "SetItem",
    "BooleanIndexFlattened",
    "VIndexArray",
    "_vindex",
    "_vindex_array",
    "_numpy_vindex",
    "normalize_index",
]
