{% set major_minor_patch = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').split('.') %}
{% set new_patch = major_minor_patch[2] | int + 1 %}
{% set version = (major_minor_patch[:2] + [new_patch]) | join('.') + environ.get('VERSION_SUFFIX', '') %}


package:
  name: dask-core
  version: {{ version }}

source:
  git_url: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python
  string: py_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask = dask.__main__:main

requirements:
  host:
    - python >=3.9
    - pip
    - versioneer =0.29
    - tomli # [py<311]

  run:
    - python >=3.9
    - click >=8.1
    - cloudpickle >=1.5.0
    - fsspec >=2021.09.0
    - packaging >=20.0
    - partd >=1.2.0
    - pyyaml >=5.3.1
    - toolz >=0.10.0
    - importlib_metadata >=4.13.0

test:
  imports:
    - dask
  commands:
    - pip check
    - dask docs --help
    - dask info --help
    - dask info versions --help
  requires:
    - pip

about:
  home: https://github.com/dask/dask/
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - dask/array/NUMPY_LICENSE.txt
  summary: Parallel Python with task scheduling
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask
