name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - packaging=20.0
  - python=3.10
  - pyyaml=5.4.1
  - click=8.1
  - cloudpickle=3.0.0
  - partd=1.4.0
  - fsspec=2021.09.0
  - importlib-metadata=4.13.0
  - toolz=0.10.0
  # optional dependencies pulled in by pip install dask[dataframe]
  - numpy=1.24
  - pandas=2.0
  - pyarrow=14.0.1
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-rerunfailures
  - pytest-timeout
  - pytest-xdist
