package:
  name: dask
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.7.4') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  path: ../

requirements:
  build:
    - python
    - pip
    - setuptools
    - toolz

  run:
    - python
    - toolz
    - numpy
    - pandas
    - pyzmq
    - dill
    - partd
    - chest

test:
  requires:
    - pytest

about:
  home: https://github.com/blaze/dask
  summary: Task scheduling and blocked algorithms for parallel processing.
  license: BSD
