name: Additional

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: additional-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doctest:
    runs-on: "ubuntu-latest"
    timeout-minutes: 90
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: v0.68.1
          environments: default
          cache: true
          locked: true

      - name: Run tests
        run: pixi r doctest
