name: Conda build

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: conda-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda:
    name: Build (and upload)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: v0.68.1
          environments: build
          cache: true
          locked: true
      
      - name: Build conda package
        shell: bash -l {0}
        run: |
          # suffix for nightly package versions
          export VERSION_SUFFIX=a`date +%y%m%d`

          pixi r conda-build

      - name: Upload conda build artifact
        uses: actions/upload-artifact@v7
        with:
          name: conda-channel
          path: dist/conda
          if-no-files-found: error

      - name: Upload conda package
        if: github.event_name == 'push' && github.repository == 'dask/dask'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.DASK_CONDA_TOKEN }}
        run: pixi r conda-upload
