name: Tests

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:
  schedule:
    # Rerun CI in order to detect flaky tests. Note that all packages are pinned, so
    # these scheduled runs are unaffected by upstream releases.
    # The upstream.yml workflow will instead pick up upstream changes.
    - cron: "0 6,18 * * *"

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.environment }} ${{ matrix.task }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        # Note: after adding/removing builds here, update
        # codecov.yml to match.
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest]
        environment: [py310, py311, py312, py313, py314]
        task: [test-ci]
        include:
          # MacOS CI does not have many hosts available; run it on 3.14 only
          - os: macos-latest
            environment: py314
            task: test-ci
          # Minimum dependencies
          - os: ubuntu-latest
            environment: mindeps-array
            task: test-ci
          - os: ubuntu-latest
            environment: mindeps-dataframe
            task: test-ci
          - os: ubuntu-latest
            environment: mindeps-distributed
            task: test-ci
          - os: ubuntu-latest
            environment: mindeps-non-optional
            task: test-ci
          - os: ubuntu-latest
            environment: mindeps-optional
            task: test-ci
          # Experimental setups
          - os: ubuntu-latest
            environment: py314
            task: test-array-expr
          - os: ubuntu-latest
            environment: mindeps-array
            task: test-array-expr
          - os: ubuntu-latest
            environment: py314t
            task: test-ci

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Needed by codecov.io

      - uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: v0.68.1
          environments: ${{ matrix.environment }}
          cache: true
          locked: true
          # post-cleanup fails on Windows:
          # EPERM: operation not permitted, unlink 'D:\a\dask\dask\.pixi\envs\py310\python.exe'
          post-cleanup: ${{ matrix.os != 'windows-latest' }}

      - name: Reconfigure pytest-timeout
        # No SIGALRM available on Windows
        if: ${{ matrix.os != 'windows-latest' }}
        run: sed -i.bak 's/timeout_method = "thread"/timeout_method = "signal"/' pyproject.toml

      - name: Run tests
        id: run_tests
        run: pixi run -e ${{ matrix.environment }} ${{ matrix.task }}
  
      - name: Coverage
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results
        # ensure this runs even if pytest fails
        if: >
          always() &&
          (steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure')
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}-${{ matrix.environment }}-${{ matrix.task }}
          path: pytest.xml

  # Publish an artifact for the event; used by publish-test-results.yaml
  event_file:
    # Do not run the schedule job on forks
    if: github.repository == 'dask/dask' || github.event_name != 'schedule'
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: Event File
          path: ${{ github.event_path }}
