name: Upstream

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: upstream-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        environment: [py314, nightly]
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Invalidate pixi lock
        run: rm -f pixi.lock

      - uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: v0.68.1
          environments: ${{ matrix.environment }}
          cache: false
          locked: false

      - name: Reconfigure pytest-timeout
        # No SIGALRM available on Windows
        run: sed -i.bak 's/timeout_method = "thread"/timeout_method = "signal"/' pyproject.toml

      - name: Run tests
        id: run_tests
        run: pixi run -e ${{ matrix.environment }} test-ci --report-log output-log.jsonl

      - name: Open or update issue on failure
        if: |
          failure()
          && github.event_name != 'pull_request'
          && github.repository == 'dask/dask'
          && steps.run_tests.outcome == 'failure'
        uses: scientific-python/issue-from-pytest-log-action@v1.5.0
        with:
          log-path: output-log.jsonl
          issue-title: ⚠️ Upstream CI failed ⚠️
          issue-label: upstream

      - name: Coverage
        uses: codecov/codecov-action@v6
